### PR TITLE
for #94, for #95: more ui updates

### PR DESCRIPTION
**Pull request by groovecoder**
Fixes (so far) as close to the mockups from #94 as I can make it:

* Text margin added to the "Remove this Container?" confirm panel
* Text size, wrapping, and overflow cleaned up in "Currently opened tabs" panel
* Back and forward arrows changed to an actual arrow svg image

### CODE REVIEW

**Comment by pdehaan** [comment]
Fails CSS linting:

```sh
> testpilot-containers@0.0.1 lint:css /Users/pdehaan/dev/github/mozilla/testpilot-containers
> stylelint webextension/css/*.css

webextension/css/popup.css
 314:3   ✖  Unexpected property "max-width"                                       property-blacklist
 338:21  ✖  Expected double colon pseudo-element notation                         selector-pseudo-element-colon-notation
 340:3   ✖  Expected "background" to come before "content"                        declaration-block-properties-order
 344:3   ✖  Expected "block-size" to come before "float"                          declaration-block-properties-order
 347:3   ✖  Expected "margin-inline-end" to come before "transform"               declaration-block-properties-order
 356:3   ✖  Expected "padding-inline-end" to come before "padding-inline-start"   declaration-block-properties-order
 361:3   ✖  Expected "color" to come before "font-size"                           declaration-block-properties-order
 361:10  ✖  Expected "#000000" to be "#000"                                       color-hex-length
```

There are also a couple ESLint errors, but those should be fixed by my unrelated PR.

**Comment by groovecoder** [comment]
Fixed `stylelint` rules.

**Comment by groovecoder** [comment]
@kjozwiak This fixes everything in #95 except for adding new colors, which I think should be a follow-up issue with needs:UX and needs:Product.

This doesn't quite implement everything in #94 so I'm leaving that open for now. But this is ready to merge for all of #94.

**Comment by kjozwiak** [comment]
@groovecoder awesome \o/.... Once this merges into master, I'll go through all the visual issues that I've added in #95 and mark the ones that have been fixed as "Completed".

I've removed the one about adding new colours from #95 and created #131.. However,  I don't have the permissions to add the needs:UX and needs:Product labels.

**Comment by pdehaan** [comment]
A minor UI issue w/ long titles...

nightly_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director__no_reason_provided_https___t_co_jto98hhw6w_

nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director__no_reason_p

---

Longer titles cause the `>` to get smaller:

nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director__no_reason_p

... plus things start wrapping and breaking w/ underflow:

nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director__no_reason_p

---

The `>` is approaching infinity, the longer the text is:

nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers

---

The `+` hover menu truncates (which looks fine):

nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers

---

Hovering over File > New Container Tab doesn't bring up a floating menu, giving me a specific container tab to open:

file_and_menubar

**Comment by pdehaan** [comment]
Possibly unrelated to this specific PR (or not), but we may also want to consider a better empty state for container tabs with no tabs. Maybe set a min-height and have some option to open a new tab for the empty container:

nightly_and_re___mozilla_testpilot-containers__hide_tabs____close_tabs___46__-_peterdehaan_gmail_com_-_gmail

... because _that_ ^^ isn't a super great user experience.

---

menubar_and_nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director_

(versus this improved UX for tab containers with 1+ open tabs)

**Comment by kjozwiak** [comment]
> Hovering over File > New Container Tab doesn't bring up a floating menu, giving me a specific container tab to open

Created #127 earlier today.. Seems macOS specific. @pdehaan, were you on macOS?

**Comment by groovecoder** [comment]
@pdehaan - can you file 2 new separate issues for those? 1. Truncate long container names in popup UI 2. Improve empty "container tab list" panel (needs:Product and/or needs:UX) ?

**Pull request merged**
