### PR TITLE
Experiment extension

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by groovecoder** [comment]
Heh, that's a lot of extra merge commits. 😉

**Comment by jonathanKingston** [comment]
Yeah I had to unfix then refix after squashing a merge locally then pulling again :(

**Comment by jonathanKingston** [comment]
@groovecoder to clarify I squashed them here anyway.

Do you think we can merge this so we can get going with testing through all the API's together with your code? Did you say you were able to ship all the code as one XPI?

**Comment by groovecoder** [comment]
Yeah I'll plan to merge this branch into master and then rebase my latest on it.

**Comment by groovecoder** [comment]
When I get up tomorrow morning. ;)

**Pull request merged**
