### PR TITLE
Changing current tab truncation to prevent container overflowing. Fix…

### PR DESCRIPTION
**Pull request by jonathanKingston**
…es #552

### CODE REVIEW

**Comment by groovecoder** [comment]
Aside from the strange container name - which may have been an edge-case where I un-installed the add-on while the tab was still open - this looks good to me.

**Comment by jonathanKingston** [comment]
@groovecoder pretty sure that is a removal edge case, worth noting for @kjozwiak perhaps though.
Odd that the icon didn't load for default tab either. Seems unrelated though.

**Comment by kjozwiak** [comment]
> @groovecoder pretty sure that is a removal edge case, worth noting for @kjozwiak perhaps though.
Odd that the icon didn't load for default tab either. Seems unrelated though.

Noted! Once this lands into master, I'll do some testing based on removing/disabling the add-on to make sure there's no issues/artifacts being left behind. @groovecoder did you create an issue for the edge case that you ran into [here](https://github.com/mozilla/testpilot-containers/pull/553#pullrequestreview-41045340)?

**Comment by groovecoder** [comment]
Hmm ... I didn't create an issue, but @kjozwiak please do some extra checks that upgrading - i.e., installing the latest master branch `.xpi` on top of existing `2.3.0` doesn't delete containers. I noticed it again, but still can't quite nail down the STR.

**Pull request merged**
