### PR TITLE
Fix async favicon service issue for <55 builds. Fixes #574

### LINKED ISSUE #566: since 2.3.0 update, can't open a new container
Hi,

I've been running using containers for a while and I really liked what I could with them (and it works fine). Since a few days ago I can't open a new container:
I click on the plugin in the toolbar I can see the list 'Personal' 'Shopping' 'Finance' and so on but when I click on one category the pop-up closes itself but it doesn't open a container. I tried to launch firefox from a terminal but it doesn't says anything.

I've another profile where it hasn't been updated and it's still 2.2.0 and there it works fine. I'm running firefox-53.0.3 on OpenBSD amd64 -current fwiw.

I hope it will get fixed soon as I really miss it :)

### LINKED ISSUE #574: View container panel doesn't open
I was able to STR in unbranded 53 on Ubuntu.

1. Open containers browser action
2. Click add button next to containers
3. Container is created
4. Go back to browser action and arrow is next to the container name
5. Click arrow

Expected:
Panel to open

Actual:
Nothing happens

This was only reproducible for me on a stale profile that already had previous versions and updated to the current 2.3.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-569)

### PR DESCRIPTION
**Pull request by jonathanKingston**
This is a **Production** merge to fix said issue. It still has broken Favicons.

### CODE REVIEW

**Comment by jonathanKingston** [comment]
As mentioned on IRC, this is for the two bugs in the commits. We can land them in Master however they seemed pretty high priority. I wasn't sure on how long Shield might take to finish now we have done the initial work etc.

**Comment by groovecoder** [comment]
I verified this fixes #564 but I can't reproduce https://github.com/mozilla/testpilot-containers/issues/566#issuecomment-305444672 nor see if this fixes it.

**Comment by jonathanKingston** [comment]
#566 is hard to repro, @kjozwiak were you able to get this on a stale profile at all?

**Comment by jonathanKingston** [comment]
Like I saw the Favicon service code, I have no idea how it actually works for some people.

**Comment by kjozwiak** [comment]
> I verified this fixes #564 but I can't reproduce https://github.com/mozilla/testpilot-containers/issues/566#issuecomment-305444672 nor see if this fixes it.

Same results. I reproduced #564 several times using the following platforms:

* Ubuntu 16.04.2 LTS using 2.3.0 under fx53.0.3 - Reproduced
* macOS 10.12.5 x64 using 2.3.0 under fx54.0b13 - Reproduced
* Win 10 x64 using 2.3.0 under fx55.0a1 - Reproduced

Using  the `production_favicon-async-issue` branch on `jonathanKingston/testpilot-containers`, I went through the following platforms to ensure that #564 was fixed:

* Ubuntu 16.04.2 LTS x64 using an unbranded fx53.0.3 - PASSED
* macOS 10.12.5 x64 using an unbranded fx54.0b15 - PASSED
* Win 10 x64 using fx55.0a1 - PASSED

Regarding #566, still attempting to reproduce.

**Comment by jonathanKingston** [comment]
Renamed commits to reflect the #566 move to #574. Also changed comments elsewhere to remove confusion.

**Comment by jonathanKingston** [comment]
It's dead on arrival.

Closing @groovecoder

**Pull request closed without merging**
