### PR TITLE
Exchanging Ctrl+Y for Ctrl+Comma due to text field collisions. Fixes …

### PR DESCRIPTION
**Pull request by jonathanKingston**
…#546

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Got any better suggestions? We could make it Ctrl+Comma on mac too if you like?

**Comment by groovecoder** [comment]
On this branch with `Ctrl+Comma` specified, the keyboard shortcut didn't work. Do we have to specify different shortcuts for the different platforms? Cmd+Y makes sense to me because it's right next to Cmd+T for new-tab.

Maybe Cmd+. ?

**Comment by groovecoder** [comment]
Cmd+Shift+O is right next to Cmd+Shift+P for Private Browsing window ...

**Comment by jonathanKingston** [comment]
Ctrl+Shift+O is open library.
Ctrl/Cmd+Y is a text operation which is why we suffer these issues.

We can set specific ones for different platforms yeah, by default Ctrl is Cmd on mac, but we can specify MacCtrl on macs.
Cmd/Ctrl+. is what I used for Sea Containers which was why I picked comma. I'm happy to yield that and not really care about mac or use Ctrl+Shift+. perhaps? I would prefer to pick something else though.

They also should override native platform ones too... I had no idea that it was preferences.

**Comment by jonathanKingston** [comment]
@groovecoder you can see the current permitted shortcuts here:
http://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/commands.json#14

They **Should** override defaults however appear not to always.

**Comment by jonathanKingston** [comment]
@groovecoder any more thoughts here?

**Comment by groovecoder** [comment]
Afraid not ... maybe Cmd+Shift+C for 'Containers' ?

**Comment by jonathanKingston** [comment]
@groovecoder nah that opens console for me.
Perhaps Ctrl+. and change Sea Containers to Ctrl+, / Ctrl+Shift+.

That sound ok?

**Comment by groovecoder** [comment]
Yeah `Ctrl` + `.` works for me.

**Comment by groovecoder** [comment]
Though `Ctrl` + `.` is already "Stop" ... but so is `Esc` ...

**Comment by jonathanKingston** [comment]
Stop for what?

**Comment by groovecoder** [comment]
Stop loading the page.

**Comment by jonathanKingston** [comment]
@groovecoder do you think that is an issue? I have never used it, I thought it was escape. Perhaps it is mac specific?

I think the only decent options are:

- Mac: Cmd+.
- Linux/Win Ctrl+.

Or

- Linux/Win/Mac Ctrl+.

Sea containers can use Shift for the above.

**Comment by groovecoder** [comment]
Let's do `Cmd`+`.` on Mac, `Ctrl`+`.` on Linux/Win.

**Comment by jonathanKingston** [comment]
I have merged this into Sea containers to be Shift for the same. However it hasn't released yet (assuming we will have a few users overlap here). I think this is safe to merge. I will try and get a release of Sea Containers out this week with more features as releasing just a regression of a keyboard shortcut is likely not cool.

**Comment by jonathanKingston** [comment]
As agreed with @kjozwiak this is easier to manage as one commit as they are all related. #576 is all shield work merged into one

**Pull request closed without merging**
