### PR TITLE
add four more icons

### PR DESCRIPTION
**Pull request by johngruen**
@jonathanKingston

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Rebase needed? LGTM though :) assuming it works :)

**Comment by johngruen** [comment]
screen shot 2017-02-21 at 2 21 01 pm
screen shot 2017-02-21 at 2 21 18 pm

**Comment by johngruen** [comment]
@jonathanKingston totally

**Comment by dave-kennedy** [comment]
@johngruen where did you get these icons? Or did you draw them yourself?

**Pull request merged**
