### PR TITLE
Long press

### PR DESCRIPTION
**Pull request by bakulf**

### CODE REVIEW

**Comment by bakulf** [comment]
Issue #130

**Comment by groovecoder** [comment]
Can't reproduce the original issue on 51; is this a 52-only bug?

**Comment by bakulf** [comment]
Yes, it's only in nightly.

**Comment by groovecoder** [comment]
The code here looks good. @pdehaan or @kjozwiak - can either of you spot-check on 52? I'm keeping my setup with 51 while I code to stick with the release experience.

**Comment by kjozwiak** [comment]
> Long-press doesn't exist in 51, right? So I assume this is a 52-only bug?

This was only affecting fx52.. I couldn't reproduce it while using fx51..

@bakulf, it looks like this is still broken in fx52.. I double checked and made sure I was running the latest code that included your fix:

> kjozwiak:testpilot-containers kjozwiak$ git log
> commit 227dbb02f1f52f8476deb679a6410cecc780b6dd
> Merge: b406557 33b9881
> Author: Andrea Marchesini <baku@ippolita.net>
> Date:   Fri Feb 3 00:13:49 2017 +0100
> 
> Merge pull request #135 from bakulf/longPress

I checked my index.js file and it looks like the pref was removed..

code

I also checked about:config and couldn't find `privacy.usercontext.longPressBehavior` anywhere... So I'm not really sure why this is still reproducible under fx52 :/

config

Thoughts?

**Pull request merged**
