### PR TITLE
Fixing usability of new tab popup. Fixes #52

### LINKED ISSUE #52: Follow up new tab/plus button fixes
After #51 we need:
- new tab css fix for down arrow
- icon fixes
- other changes to make it match the mockup

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by jonathanKingston** [comment]
@groovecoder the latest patch pushed isn't tested on Mac either however it should solve the issue above (I did rudimentary testing of what caused that issue and continued the work in Ubuntu - will test tomorrow).

**Comment by jonathanKingston** [comment]
Also should fix #111. @groovecoder could you take another look at this as I think this is now landable it fixes all the linked issues and for mac.

**Comment by jonathanKingston** [comment]
Gonna merge this as it is blocking my linting patch.

**Comment by groovecoder** [comment]
Yup, the issues I saw are resolved here. But #111 still happens ...

testpilot-containers-mac-ui-tab-plus-hover

**Comment by jonathanKingston** [comment]
@groovecoder yeah I was seeing that also. Let's keep #111 open but close off this and all the others :).

**Pull request merged**
