### PR TITLE
for #598: stop calling getCurrentPingData

### PR DESCRIPTION
**Pull request by groovecoder**
See https://github.com/mozilla/testpilot/commit/fa0f73fd6a0911f54366e3c8bef836995d4491fe

### CODE REVIEW

**Comment by jonathanKingston** [comment]
This LGTM but not sure if there are other side effects? You mentioned you wanted to delay merging this, is there any reason?

**Comment by groovecoder** [comment]
I just prefer to avoid any code-churn while we're in the final stretch of code + QA for the shield study.

**Comment by jonathanKingston** [comment]
Adding DNM based on recent meeting.

**Comment by jonathanKingston** [comment]
@groovecoder we should probably merge this, the current code removes all telemetry anyway. (file a follow up if you want it back for test pilot)

**Comment by jonathanKingston** [comment]
Closing as ripping it out instead, sorries @groovecoder

**Pull request closed without merging**
