### PR TITLE
Fix the opening of a link from a context menu - issue #327

### PR DESCRIPTION
**Pull request by bakulf**

### CODE REVIEW

**Comment by groovecoder** [comment]
This doesn't seem to fix issue #327 for me? Cmd+Click & Middle-Click still open the link in the default/non-container context.

container-newtab-middle-cmd-click

**Comment by groovecoder** [comment]
This **does** fix https://github.com/mozilla/testpilot-containers/issues/327#issuecomment-285004995 ... but not the cmd/ctrl+click nor middle-click issues.

**Comment by bakulf** [comment]
@groovecoder, Do you mind to land this and then we can fix the rest of #327 in a separate PR ?

**Comment by shavounet** [comment]
I can confirm it has been partially resolved for right-click, and not ctrl-click (Firefox 52, Container 2.0) (though I lost icons ? but it may be unrelated...)
selection_106

**Pull request merged**
