### PR TITLE
Move to new window should show hidden tabs as well - issue #257

### PR DESCRIPTION
**Pull request by bakulf**

### CODE REVIEW

**Comment by groovecoder** [comment]
This is a fix, but doesn't fix to the "Expected result" in https://github.com/mozilla/testpilot-containers/issues/257. @johngruen or @TanviHacks - what behavior do we want here?

**Comment by groovecoder** [comment]
In addition, if we disable the "Move to new window" feature completely, we may not want to merge this.

**Comment by bakulf** [comment]
I think we want to merge this doesn't matter what. It's nice to have. In the end, if I want to move tabs in a separate window, why should I do it with 2 clicks?

**Comment by bakulf** [comment]
after the meeting, it seems we are happy with this patch, right? :)

**Comment by TanviHacks** [comment]
When tabs are hidden and we select move tabs, the tabs should be both moved
and shown

**Pull request merged**
